## **Bias Data Analysis**

Import Dataset

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Biased.csv")

In [3]:
df.head()

,Id,gender,age,nationality,sport,ind-university_grade,ind-debateclub,ind-programming_exp,ind-international_exp,ind-entrepeneur_exp,ind-languages,ind-exact_study,ind-degree,company,decision
0,x8011e,female,24,German,Swimming,70,False,False,False,False,1,True,phd,A,True
1,x6077a,male,26,German,Golf,67,False,True,False,False,2,True,bachelor,A,False
2,x6006e,female,23,Dutch,Running,67,False,True,True,False,0,True,master,A,False
3,x2173b,male,24,Dutch,Cricket,70,False,True,False,False,1,True,master,A,True
4,x6241a,female,26,German,Golf,59,False,False,False,False,1,False,master,A,True

Dataset Shape

In [4]:
df.shape

(4000, 15)

Column Overview

In [5]:
df.columns.tolist()

['Id',
 'gender',
 'age',
 'nationality',
 'sport',
 'ind-university_grade',
 'ind-debateclub',
 'ind-programming_exp',
 'ind-international_exp',
 'ind-entrepeneur_exp',
 'ind-languages',
 'ind-exact_study',
 'ind-degree',
 'company',
 'decision']

Data Types Classification

In [6]:
df.dtypes.tolist()

[dtype('O'),
 dtype('O'),
 dtype('int64'),
 dtype('O'),
 dtype('O'),
 dtype('int64'),
 dtype('bool'),
 dtype('bool'),
 dtype('bool'),
 dtype('bool'),
 dtype('int64'),
 dtype('bool'),
 dtype('O'),
 dtype('O'),
 dtype('bool')]

Missing Value Percentage

In [7]:
missing_pct = df.isna().mean().sort_values(ascending=False)
missing_pct

Id                       0.0
gender                   0.0
age                      0.0
nationality              0.0
sport                    0.0
ind-university_grade     0.0
ind-debateclub           0.0
ind-programming_exp      0.0
ind-international_exp    0.0
ind-entrepeneur_exp      0.0
ind-languages            0.0
ind-exact_study          0.0
ind-degree               0.0
company                  0.0
decision                 0.0
dtype: float64

Rows with Heavy Missingness

In [8]:
row_missing_pct = df.isna().mean(axis=1)
row_missing_pct.describe()

count    4000.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
dtype: float64

Identify Target Column

In [9]:
target_column = 'decision'

Target Balance

In [10]:
df[target_column].value_counts(normalize=True)

decision
False    0.68325
True     0.31675
Name: proportion, dtype: float64

Separate Numeric & Categorical Columns

In [11]:
numeric_cols = df.select_dtypes(include="number").columns.tolist()
categorical_cols = df.select_dtypes(exclude="number").columns.tolist()

numeric_cols, categorical_cols

(['age', 'ind-university_grade', 'ind-languages'],
 ['Id',
  'gender',
  'nationality',
  'sport',
  'ind-debateclub',
  'ind-programming_exp',
  'ind-international_exp',
  'ind-entrepeneur_exp',
  'ind-exact_study',
  'ind-degree',
  'company',
  'decision'])

Feature–Target Relationship Scan

In [12]:
group_columns = [ 
  'gender',
  'nationality',
  'sport',
]

In [13]:
baseline_rate = df[target_column].mean()
baseline_rate

np.float64(0.31675)

In [14]:
for col in group_columns:
    print(f"\nBias check for: {col}")
    print(df.groupby(col)[target_column].mean())

Bias check for: gender
gender
female    0.274860
male      0.352609
other     0.301205
Name: decision, dtype: float64

Bias check for: nationality
nationality
Belgian    0.308756
Dutch      0.318598
German     0.310777
Name: decision, dtype: float64

Bias check for: sport
sport
Chess       0.260274
Cricket     0.299674
Football    0.353206
Golf        0.275542
Rugby       0.401481
Running     0.207120
Swimming    0.291727
Tennis      0.318284
Name: decision, dtype: float64

Group Size Check

In [15]:
for col in categorical_cols:
    print(col)
    print(df[col].value_counts(normalize=True).head())
    print("-" * 30)

Id
Id
x4189e    0.00025
x2666c    0.00025
x4578c    0.00025
x7911e    0.00025
x8015f    0.00025
Name: proportion, dtype: float64
------------------------------
gender
gender
male      0.53175
female    0.44750
other     0.02075
Name: proportion, dtype: float64
------------------------------
nationality
nationality
Dutch      0.79175
Belgian    0.10850
German     0.09975
Name: proportion, dtype: float64
------------------------------
sport
sport
Football    0.22225
Swimming    0.17225
Rugby       0.16875
Tennis      0.11075
Chess       0.09125
Name: proportion, dtype: float64
------------------------------
ind-debateclub
ind-debateclub
False    0.76475
True     0.23525
Name: proportion, dtype: float64
------------------------------
ind-programming_exp
ind-programming_exp
False    0.68
True     0.32
Name: proportion, dtype: float64
------------------------------
ind-international_exp
ind-international_exp
False    0.77575
True     0.22425
Name: proportion, dtype: float64
------------------------------
ind-entrepeneur_exp
ind-entrepeneur_exp
False    0.773
True     0.227
Name: proportion, dtype: float64
------------------------------
ind-exact_study
ind-exact_study
False    0.53725
True     0.46275
Name: proportion, dtype: float64
------------------------------
ind-degree
ind-degree
bachelor    0.49600
master      0.44225
phd         0.06175
Name: proportion, dtype: float64
------------------------------
company
company
A    0.25
B    0.25
C    0.25
D    0.25
Name: proportion, dtype: float64
------------------------------
decision
decision
False    0.68325
True     0.31675
Name: proportion, dtype: float64
------------------------------

Representation vs Outcome Share

In [16]:
for col in group_columns:
    print(f"\nRepresentation vs outcome for {col}")
    print("Representation:")
    print(df[col].value_counts(normalize=True))
    print("Outcome share:")
    print(df[df[target_column] == True][col].value_counts(normalize=True))

Representation vs outcome for gender
Representation:
gender
male      0.53175
female    0.44750
other     0.02075
Name: proportion, dtype: float64
Outcome share:
gender
male      0.591949
female    0.388319
other     0.019732
Name: proportion, dtype: float64

Representation vs outcome for nationality
Representation:
nationality
Dutch      0.79175
Belgian    0.10850
German     0.09975
Name: proportion, dtype: float64
Outcome share:
nationality
Dutch      0.796369
Belgian    0.105762
German     0.097869
Name: proportion, dtype: float64

Representation vs outcome for sport
Representation:
sport
Football    0.22225
Swimming    0.17225
Rugby       0.16875
Tennis      0.11075
Chess       0.09125
Golf        0.08075
Running     0.07725
Cricket     0.07675
Name: proportion, dtype: float64
Outcome share:
sport
Football    0.247830
Rugby       0.213891
Swimming    0.158642
Tennis      0.111287
Chess       0.074980
Cricket     0.072612
Golf        0.070245
Running     0.050513
Name: proportion, dtype: float64

Small group risk

In [22]:
df[group_columns].value_counts()

gender  nationality  sport
male    Dutch        Football    497
                     Rugby       411
female  Dutch        Swimming    341
                     Chess       261
                     Football    199
                                ...
other   Belgian      Golf          1
        German       Football      1
                     Rugby         1
                     Running       1
                     Swimming      1
Name: count, Length: 66, dtype: int64

Basic Distribution Sanity

In [17]:
df[numeric_cols].describe().T

                       count      mean       std   min   25%   50%   75%   max
age                   4000.0  26.17900  2.807477  21.0  24.0  26.0  28.0  32.0
ind-university_grade  4000.0  62.38000  5.916194  45.0  58.0  62.0  67.0  78.0
ind-languages         4000.0   1.33625  0.854031   0.0   1.0   1.0   2.0   3.0

Identifier & Time Column Detection

In [18]:
[col for col in df.columns if "id" in col.lower() or "date" in col.lower() or "time" in col.lower()]

['Id']

## Dataset Verdict — Phase 3
  
**Dataset Role:** Bias


### Target Column
- **Target:** Decision  
- **Target Type:** Boolean