## **Messy Data Analysis**

Import Dataset

In [74]:
import pandas as pd

In [75]:
df = pd.read_csv('messy dataset.csv')

In [76]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [77]:
df.shape

(20, 11)

Column name normalization

In [78]:
df.columns = df.columns.str.strip().str.replace("\n", " ", regex=False)

Schema & Data types

In [79]:
df.columns.tolist()

['Rank',
 'Peak',
 'All Time Peak',
 'Actual\xa0gross',
 'Adjusted\xa0gross (in 2022 dollars)',
 'Artist',
 'Tour title',
 'Year(s)',
 'Shows',
 'Average gross',
 'Ref.']

In [80]:
df.dtypes

Rank                                 int64
Peak                                object
All Time Peak                       object
Actual gross                        object
Adjusted gross (in 2022 dollars)    object
Artist                              object
Tour title                          object
Year(s)                             object
Shows                                int64
Average gross                       object
Ref.                                object
dtype: object

Target Column

In [81]:
target_column = 'Average gross'

Target Validation

In [89]:
df[target_column].dtype
df[target_column].isna().mean()
df[target_column].value_counts()

Average gross
13928571    1
10353571    1
4835294     1
2546795     1
6522173     1
3467709     1
2137405     1
6282927     1
5226215     1
2945882     1
1735606     1
1118227     1
1350993     1
615385      1
3233333     1
1295775     1
1734694     1
2070732     1
1385950     1
1744186     1
Name: count, dtype: int64

Missingness Analysis

In [90]:
df.isna().mean()
df.isna().mean(axis=1)

0     0.000000
1     0.000000
2     0.000000
3     0.000000
4     0.090909
5     0.000000
6     0.090909
7     0.181818
8     0.181818
9     0.181818
10    0.272727
11    0.090909
12    0.181818
13    0.090909
14    0.090909
15    0.181818
16    0.181818
17    0.181818
18    0.272727
19    0.181818
dtype: float64

Converting Currency columns to Numeric columns

In [82]:
currency_columns = ['Actual\xa0gross', 'Average gross' , 'Adjusted\xa0gross (in 2022 dollars)']

In [83]:
for col in currency_columns:
    df[col] = (
        df[col]
        .str.replace("$", "", regex=False)
        .str.replace(",", "", regex=False)
    )
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [84]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,780000000.0,780000000,Taylor Swift,The Eras Tour †,2023–2024,56,13928571,[1]
1,2,1,7[2],579800000.0,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,[3]
2,3,1[4],2[5],411000000.0,560622615,Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,4835294,[6]
3,4,2[7],10[7],397300000.0,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,[7]
4,5,2[4],NaN,345675146.0,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,[8]

Category Noise

In [85]:
df[target_column].value_counts()
df[target_column].nunique()

20

Invalid / Placeholder Values

In [86]:
df[target_column].unique()

array([13928571, 10353571,  4835294,  2546795,  6522173,  3467709,
        2137405,  6282927,  5226215,  2945882,  1735606,  1118227,
        1350993,   615385,  3233333,  1295775,  1734694,  2070732,
        1385950,  1744186])

Identifier & Leakage Risk

In [87]:
df[target_column].nunique() / len(df)

1.0

Distribution Check

In [88]:
df[target_column].describe()

count    2.000000e+01
mean     3.726571e+06
std      3.393340e+06
min      6.153850e+05
25%      1.647508e+06
50%      2.342100e+06
75%      4.933024e+06
max      1.392857e+07
Name: Average gross, dtype: float64

## Dataset Verdict — Phase 3
  
**Dataset Role:** Messy


### Target Column
- **Target:** Average gross  
- **Target Type:** numeric